//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStatistic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrossZeroStat
    {
        public int GameId { get; set; }
        public string Marker { get; set; }
        public int CounterUserSteps { get; set; }
        public string Winner { get; set; }
        public System.DateTime Date { get; set; }
    }
}
